INFO 2021-01-28 10:42:19,240 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 10:42:22,384 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'code'
ERROR 2021-01-28 10:42:22,386 basehttp 154 "GET /sms_codes/15838618208/?uuid=2906a4b6-42af-4b8d-8b00-14025c3b976b&image_code=QS9L HTTP/1.1" 500 79202
INFO 2021-01-28 10:44:16,090 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 10:44:19,158 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'code'
ERROR 2021-01-28 10:44:19,160 basehttp 154 "GET /sms_codes/15838618208/ HTTP/1.1" 500 78256
INFO 2021-01-28 10:44:42,532 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\urls.py changed, reloading.
INFO 2021-01-28 10:44:46,613 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 10:44:55,726 log 228 Internal Server Error: /sms_codes/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 2 required positional arguments: 'code' and 'mobile'
ERROR 2021-01-28 10:44:55,728 basehttp 154 "GET /sms_codes/ HTTP/1.1" 500 77906
INFO 2021-01-28 10:45:40,112 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-28 10:45:44,480 log 228 Not Found: /sms_codes/15838618208/
WARNING 2021-01-28 10:45:44,481 basehttp 154 "GET /sms_codes/15838618208/?uuid=2906a4b6-42af-4b8d-8b00-14025c3b976b&image_code=QS9L HTTP/1.1" 404 2677
INFO 2021-01-28 10:46:30,077 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:46:32,441 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:46:35,100 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:46:37,383 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:46:54,908 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:47:00,128 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-28 10:47:04,798 log 228 Not Found: /sms_codes/15838618208/
WARNING 2021-01-28 10:47:04,799 basehttp 154 "GET /sms_codes/15838618208/?uuid=2906a4b6-42af-4b8d-8b00-14025c3b976b&image_code=QS9L HTTP/1.1" 404 2677
INFO 2021-01-28 10:47:14,450 basehttp 154 "GET /users/register/ HTTP/1.1" 200 3836
INFO 2021-01-28 10:47:14,724 basehttp 154 "GET /image_codes/c291665a-18a7-43c0-b8b4-0388245c7653/ HTTP/1.1" 200 3399
WARNING 2021-01-28 10:48:05,489 log 228 Not Found: /sms_codes/15838618208/
WARNING 2021-01-28 10:48:05,490 basehttp 154 "GET /sms_codes/15838618208/?uuid=c291665a-18a7-43c0-b8b4-0388245c7653&image_code=ZUFU HTTP/1.1" 404 2677
INFO 2021-01-28 10:48:40,156 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 10:48:44,796 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'code'
ERROR 2021-01-28 10:48:44,798 basehttp 154 "GET /sms_codes/15838618208/?uuid=c291665a-18a7-43c0-b8b4-0388245c7653&image_code=ZUFU HTTP/1.1" 500 79202
INFO 2021-01-28 10:49:55,543 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:49:56,969 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:50:07,642 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:50:09,033 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:50:15,165 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 10:50:16,692 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() missing 1 required positional argument: 'code'
ERROR 2021-01-28 10:50:16,694 basehttp 154 "GET /sms_codes/15838618208/?uuid=c291665a-18a7-43c0-b8b4-0388245c7653&image_code=ZUFU HTTP/1.1" 500 79202
INFO 2021-01-28 10:50:56,229 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 10:50:57,639 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:51:09,681 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\libs\ronglianyun\ccp_sms.py changed, reloading.
INFO 2021-01-28 10:51:11,063 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 10:51:13,211 basehttp 154 "GET /sms_codes/15838618208/?uuid=c291665a-18a7-43c0-b8b4-0388245c7653&image_code=ZUFU HTTP/1.1" 200 84
INFO 2021-01-28 10:52:24,943 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 10:52:26,384 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:22:45,772 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:22:47,206 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:23:31,167 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:23:32,630 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:23:54,125 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:23:55,476 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:24:12,996 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:24:15,796 basehttp 154 "GET /users/register/ HTTP/1.1" 200 3836
INFO 2021-01-28 14:24:16,171 basehttp 154 "GET /image_codes/d994c8e1-4ec3-47a1-9078-d55d2b3da7ad/ HTTP/1.1" 200 3154
ERROR 2021-01-28 14:24:51,595 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py", line 56, in get
    iamge_code_server = image_code_client.decode()
AttributeError: 'str' object has no attribute 'decode'
ERROR 2021-01-28 14:24:51,597 basehttp 154 "GET /sms_codes/15838618208/?uuid=d994c8e1-4ec3-47a1-9078-d55d2b3da7ad&image_code=fw46 HTTP/1.1" 500 84266
INFO 2021-01-28 14:25:19,649 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:25:21,017 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-01-28 14:25:25,438 log 228 Internal Server Error: /sms_codes/15838618208/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py", line 56, in get
    iamge_code_server = iamge_code_server.decode()
AttributeError: 'NoneType' object has no attribute 'decode'
ERROR 2021-01-28 14:25:25,440 basehttp 154 "GET /sms_codes/15838618208/?uuid=d994c8e1-4ec3-47a1-9078-d55d2b3da7ad&image_code=fw46 HTTP/1.1" 500 84275
INFO 2021-01-28 14:26:06,505 basehttp 154 "GET /users/register/ HTTP/1.1" 200 3836
INFO 2021-01-28 14:26:06,837 basehttp 154 "GET /image_codes/6285526b-96e5-41ea-8d82-7d9b9157452d/ HTTP/1.1" 200 3123
INFO 2021-01-28 14:26:45,994 basehttp 154 "GET /sms_codes/15838618208/?uuid=6285526b-96e5-41ea-8d82-7d9b9157452d&image_code=IULW HTTP/1.1" 200 63
INFO 2021-01-28 14:28:43,333 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:28:44,543 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:28:57,993 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:28:59,513 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:29:24,615 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:29:25,983 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:29:38,942 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:29:40,298 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:29:50,748 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:29:52,291 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:33:04,215 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:33:05,599 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:33:36,553 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:33:37,891 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:33:56,423 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 14:33:57,794 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:48:09,101 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 14:48:35,219 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-01-28 14:48:35,289 basehttp 154 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2021-01-28 14:48:35,292 basehttp 154 "GET /static/css/main.css HTTP/1.1" 200 40091
INFO 2021-01-28 14:48:35,338 basehttp 154 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-01-28 14:48:35,338 basehttp 154 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2021-01-28 14:48:35,338 basehttp 154 "GET /static/js/register.js HTTP/1.1" 200 7453
INFO 2021-01-28 14:48:35,340 basehttp 154 "GET /static/images/1.png HTTP/1.1" 200 3555
INFO 2021-01-28 14:48:35,341 basehttp 154 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2021-01-28 14:48:35,464 basehttp 154 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2021-01-28 14:48:35,464 basehttp 154 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2021-01-28 14:48:35,465 basehttp 154 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
INFO 2021-01-28 14:48:35,568 basehttp 154 "GET /image_codes/f6795471-678c-4d78-81a6-19bb57f4ea5a/ HTTP/1.1" 200 3637
WARNING 2021-01-28 14:48:37,939 log 228 Not Found: /favicon.ico
WARNING 2021-01-28 14:48:37,939 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-01-28 14:48:39,435 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 14:48:48,883 basehttp 154 "GET /image_codes/ccc39935-e75d-468a-95f3-dfc554e2aade/ HTTP/1.1" 200 3252
INFO 2021-01-28 14:48:51,405 basehttp 154 "GET /image_codes/00d181e1-65f5-426e-a57e-aaa7fef8c275/ HTTP/1.1" 200 3103
INFO 2021-01-28 14:48:57,659 basehttp 154 "GET /sms_codes/15838618208/?uuid=00d181e1-65f5-426e-a57e-aaa7fef8c275&image_code=ngud HTTP/1.1" 200 63
INFO 2021-01-28 14:49:14,047 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 14:49:14,051 basehttp 154 "POST /users/register/ HTTP/1.1" 200 5813
INFO 2021-01-28 14:49:14,295 basehttp 154 "GET /image_codes/4a6ff640-cc64-4be6-b735-3a120eb9c11f/ HTTP/1.1" 200 3463
WARNING 2021-01-28 14:52:14,141 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 14:52:15,148 basehttp 154 "POST /users/register/ HTTP/1.1" 200 5813
WARNING 2021-01-28 14:52:15,375 log 228 Not Found: /users/images/interval_line.png
WARNING 2021-01-28 14:52:15,376 log 228 Not Found: /users/images/register_banner.png
WARNING 2021-01-28 14:52:15,377 log 228 Not Found: /users/images/icons02.png
WARNING 2021-01-28 14:52:15,378 basehttp 154 "GET /users/images/interval_line.png HTTP/1.1" 404 2953
WARNING 2021-01-28 14:52:15,378 basehttp 154 "GET /users/images/icons02.png HTTP/1.1" 404 2935
WARNING 2021-01-28 14:52:15,378 basehttp 154 "GET /users/images/register_banner.png HTTP/1.1" 404 2959
INFO 2021-01-28 14:52:15,456 basehttp 154 "GET /image_codes/962e56de-8186-4089-82cf-bc9d1de3f54c/ HTTP/1.1" 200 3037
WARNING 2021-01-28 14:52:15,461 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 14:52:22,427 basehttp 154 "POST /users/register/ HTTP/1.1" 200 5813
INFO 2021-01-28 14:52:22,748 basehttp 154 "GET /image_codes/a4697d8b-ce04-4603-bb48-c8e884114234/ HTTP/1.1" 200 3105
WARNING 2021-01-28 14:52:22,760 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 14:52:31,670 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 14:52:46,901 basehttp 154 "GET /image_codes/7d3312b8-bc65-4132-9750-6a3590a759cc/ HTTP/1.1" 200 3543
INFO 2021-01-28 14:52:53,427 basehttp 154 "GET /sms_codes/17710709974/?uuid=7d3312b8-bc65-4132-9750-6a3590a759cc&image_code=dwmw HTTP/1.1" 200 63
INFO 2021-01-28 14:53:06,848 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 14:53:06,851 basehttp 154 "POST /users/register/ HTTP/1.1" 200 5813
INFO 2021-01-28 14:53:07,175 basehttp 154 "GET /image_codes/19e443fa-26e3-463a-8793-ebca1c7fb55c/ HTTP/1.1" 200 2964
WARNING 2021-01-28 14:53:07,187 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 15:03:51,745 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:03:56,618 basehttp 154 "POST /users/register/ HTTP/1.1" 200 5810
INFO 2021-01-28 15:03:56,721 basehttp 154 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2021-01-28 15:03:56,722 basehttp 154 "GET /static/css/main.css HTTP/1.1" 200 40091
INFO 2021-01-28 15:03:56,776 basehttp 154 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2021-01-28 15:03:56,782 basehttp 154 "GET /static/js/register.js HTTP/1.1" 200 7453
INFO 2021-01-28 15:03:56,785 basehttp 154 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2021-01-28 15:03:56,785 basehttp 154 "GET /static/images/1.png HTTP/1.1" 200 3555
INFO 2021-01-28 15:03:56,787 basehttp 154 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-01-28 15:03:56,921 basehttp 154 "GET /static/images/icons.png HTTP/1.1" 200 7740
INFO 2021-01-28 15:03:56,929 basehttp 154 "GET /static/images/down.png HTTP/1.1" 200 1064
INFO 2021-01-28 15:03:56,937 basehttp 154 "GET /static/images/clock.jpg HTTP/1.1" 200 2235
INFO 2021-01-28 15:03:56,939 basehttp 154 "GET /static/images/shop_cart.png HTTP/1.1" 200 1317
INFO 2021-01-28 15:03:56,940 basehttp 154 "GET /static/images/selected.png HTTP/1.1" 200 1060
INFO 2021-01-28 15:03:56,949 basehttp 154 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2021-01-28 15:03:56,952 basehttp 154 "GET /static/images/login_banner.png HTTP/1.1" 200 319312
INFO 2021-01-28 15:03:56,953 basehttp 154 "GET /static/images/QQ-weixin.png HTTP/1.1" 200 1816
INFO 2021-01-28 15:03:56,960 basehttp 154 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2021-01-28 15:03:56,961 basehttp 154 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
INFO 2021-01-28 15:03:56,966 basehttp 154 "GET /static/images/pay_icons.png HTTP/1.1" 200 11917
INFO 2021-01-28 15:03:56,970 basehttp 154 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
INFO 2021-01-28 15:03:56,986 basehttp 154 "GET /static/images/edit.png HTTP/1.1" 200 1244
INFO 2021-01-28 15:03:57,001 basehttp 154 "GET /static/images/success.png HTTP/1.1" 200 2738
INFO 2021-01-28 15:03:57,003 basehttp 154 "GET /static/images/time_count_bg.png HTTP/1.1" 200 1332
INFO 2021-01-28 15:03:57,004 basehttp 154 "GET /static/images/stars.png HTTP/1.1" 200 2688
INFO 2021-01-28 15:03:57,004 basehttp 154 "GET /static/images/shine.png HTTP/1.1" 200 1270
INFO 2021-01-28 15:03:57,004 basehttp 154 "GET /static/images/find-password.png HTTP/1.1" 200 6186
INFO 2021-01-28 15:03:57,009 basehttp 154 "GET /static/images/arrow.png HTTP/1.1" 200 985
INFO 2021-01-28 15:03:57,037 basehttp 154 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2021-01-28 15:03:57,038 basehttp 154 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2021-01-28 15:03:57,039 basehttp 154 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
WARNING 2021-01-28 15:03:57,172 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 15:03:57,206 basehttp 154 "GET /image_codes/2609f30c-a54a-4c73-9675-ef145c55914f/ HTTP/1.1" 200 3443
WARNING 2021-01-28 15:04:00,219 log 228 Not Found: /favicon.ico
WARNING 2021-01-28 15:04:00,220 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-01-28 15:04:02,301 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 15:04:14,330 basehttp 154 "GET /sms_codes/17710709974/?uuid=2609f30c-a54a-4c73-9675-ef145c55914f&image_code=sahd HTTP/1.1" 200 63
INFO 2021-01-28 15:04:25,427 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-01-28 15:04:25,752 basehttp 154 "POST /users/register/ HTTP/1.1" 302 0
INFO 2021-01-28 15:04:25,764 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-01-28 15:04:25,833 basehttp 154 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2021-01-28 15:04:26,068 basehttp 154 "GET /static/js/index.js HTTP/1.1" 200 1143
INFO 2021-01-28 15:04:26,069 basehttp 154 "GET /static/js/slide.js HTTP/1.1" 200 1822
INFO 2021-01-28 15:04:26,114 basehttp 154 "GET /static/images/goods/goods001.jpg HTTP/1.1" 200 5391
INFO 2021-01-28 15:04:26,118 basehttp 154 "GET /static/images/goods/goods002.jpg HTTP/1.1" 200 5377
INFO 2021-01-28 15:04:26,124 basehttp 154 "GET /static/images/slide01.jpg HTTP/1.1" 200 67813
INFO 2021-01-28 15:04:26,130 basehttp 154 "GET /static/images/slide02.jpg HTTP/1.1" 200 89905
INFO 2021-01-28 15:04:26,131 basehttp 154 "GET /static/images/adv01.jpg HTTP/1.1" 200 39831
INFO 2021-01-28 15:04:26,137 basehttp 154 "GET /static/images/banner01.jpg HTTP/1.1" 200 23658
INFO 2021-01-28 15:04:26,148 basehttp 154 "GET /static/images/slide04.jpg HTTP/1.1" 200 107973
INFO 2021-01-28 15:04:26,149 basehttp 154 "GET /static/images/slide03.jpg HTTP/1.1" 200 70152
INFO 2021-01-28 15:04:26,151 basehttp 154 "GET /static/images/goods/goods004.jpg HTTP/1.1" 200 6565
INFO 2021-01-28 15:04:26,153 basehttp 154 "GET /static/images/goods/goods003.jpg HTTP/1.1" 200 8579
INFO 2021-01-28 15:04:26,160 basehttp 154 "GET /static/images/goods/goods005.jpg HTTP/1.1" 200 7578
INFO 2021-01-28 15:04:26,164 basehttp 154 "GET /static/images/banner02.jpg HTTP/1.1" 200 26729
INFO 2021-01-28 15:04:26,166 basehttp 154 "GET /static/images/banner03.jpg HTTP/1.1" 200 22681
INFO 2021-01-28 15:04:26,168 basehttp 154 "GET /static/images/goods/goods008.jpg HTTP/1.1" 200 7072
INFO 2021-01-28 15:04:26,172 basehttp 154 "GET /static/images/goods/goods009.jpg HTTP/1.1" 200 8738
WARNING 2021-01-28 15:04:26,217 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-01-28 15:19:54,117 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:19:55,545 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:27:00,989 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:27:02,212 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:27:39,830 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:27:41,287 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:28:07,639 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:28:08,999 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:29:08,033 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:29:09,302 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:30:07,702 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:30:09,076 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:30:39,142 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:30:40,359 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:30:46,098 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:30:47,332 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:31:00,851 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\constants.py changed, reloading.
INFO 2021-01-28 15:31:02,249 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:32:47,510 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\constants.py changed, reloading.
INFO 2021-01-28 15:32:48,959 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:34:00,939 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\constants.py changed, reloading.
INFO 2021-01-28 15:34:02,146 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-28 15:34:27,020 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-01-28 15:34:28,402 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 09:36:54,473 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 09:37:26,410 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 09:37:26,533 basehttp 154 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2021-02-01 09:37:26,534 basehttp 154 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-02-01 09:37:26,535 basehttp 154 "GET /static/js/register.js HTTP/1.1" 200 7453
INFO 2021-02-01 09:37:26,537 basehttp 154 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2021-02-01 09:37:26,623 basehttp 154 "GET /static/images/1.png HTTP/1.1" 200 3555
INFO 2021-02-01 09:37:27,131 basehttp 154 "GET /image_codes/fb1e6a0b-93e9-40e7-9922-fb8091adab39/ HTTP/1.1" 200 3464
WARNING 2021-02-01 09:37:28,895 log 228 Not Found: /favicon.ico
WARNING 2021-02-01 09:37:28,895 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-02-01 09:37:44,186 basehttp 154 "GET /sms_codes/17710709974/?uuid=fb1e6a0b-93e9-40e7-9922-fb8091adab39&image_code=lrhy HTTP/1.1" 200 63
INFO 2021-02-01 09:38:44,215 basehttp 154 "GET /image_codes/c695575a-915b-42c8-81aa-bb288295f4f9/ HTTP/1.1" 200 3692
INFO 2021-02-01 10:29:22,114 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:29:31,001 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
ERROR 2021-02-01 10:29:31,542 log 228 Internal Server Error: /image_codes/c28225b5-1b88-4e55-8931-29d342969569/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py", line 32, in get
    redis_conn.setex('img_%s' % uuid, text, constants.IMAGE_CODE_REDIS_EXPIRES)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\redis\client.py", line 1822, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\redis\client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
ERROR 2021-02-01 10:29:31,548 basehttp 154 "GET /image_codes/c28225b5-1b88-4e55-8931-29d342969569/ HTTP/1.1" 500 105802
INFO 2021-02-01 10:30:32,903 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-02-01 10:30:34,367 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:30:40,651 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:30:43,916 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 10:30:44,313 basehttp 154 "GET /image_codes/d58ba3f2-56e3-4d43-9472-ee8628233fd4/ HTTP/1.1" 200 2961
INFO 2021-02-01 10:30:46,492 basehttp 154 "GET /image_codes/cd14b9b4-1735-4e3a-b2f6-fabe521b305f/ HTTP/1.1" 200 3167
INFO 2021-02-01 10:37:49,196 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:37:57,285 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 10:37:57,693 basehttp 154 "GET /image_codes/f13a5909-9fc5-434b-85a3-ba166c2c35a3/ HTTP/1.1" 200 3290
INFO 2021-02-01 10:38:05,040 basehttp 154 "GET /sms_codes/15838618208/?uuid=f13a5909-9fc5-434b-85a3-ba166c2c35a3&image_code=zmcr HTTP/1.1" 200 63
INFO 2021-02-01 10:39:05,062 basehttp 154 "GET /image_codes/9350a9a6-f3d6-4983-b34a-9afcb9cabb8d/ HTTP/1.1" 200 3248
INFO 2021-02-01 10:39:40,984 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:39:49,751 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:40:01,538 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 10:40:01,925 basehttp 154 "GET /image_codes/8b839f89-7cf8-472a-a111-ddad819b5c9e/ HTTP/1.1" 200 3076
INFO 2021-02-01 10:40:06,187 basehttp 154 "GET /image_codes/ab35b460-6d42-4c74-888d-2de181aa5298/ HTTP/1.1" 200 3548
INFO 2021-02-01 10:40:14,570 basehttp 154 "GET /sms_codes/17710709974/?uuid=ab35b460-6d42-4c74-888d-2de181aa5298&image_code=80en HTTP/1.1" 200 84
INFO 2021-02-01 10:40:15,821 basehttp 154 "GET /sms_codes/17710709974/?uuid=ab35b460-6d42-4c74-888d-2de181aa5298&image_code=80en HTTP/1.1" 200 78
INFO 2021-02-01 10:40:21,450 basehttp 154 "GET /image_codes/36a91af5-c5a4-40fa-ae75-7cbc0616ecb3/ HTTP/1.1" 200 3261
INFO 2021-02-01 10:40:29,410 basehttp 154 "GET /sms_codes/17710709974/?uuid=36a91af5-c5a4-40fa-ae75-7cbc0616ecb3&image_code=lruw HTTP/1.1" 200 63
INFO 2021-02-01 10:40:57,011 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:41:00,252 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 10:41:00,605 basehttp 154 "GET /image_codes/d41ca003-e485-4afa-93f6-015856d093f9/ HTTP/1.1" 200 3122
INFO 2021-02-01 10:41:11,285 basehttp 154 "GET /sms_codes/15838618208/?uuid=d41ca003-e485-4afa-93f6-015856d093f9&image_code=j8zl HTTP/1.1" 200 63
INFO 2021-02-01 10:41:50,671 autoreload 217 C:\Users\LiZ\Desktop\lgshop\celery_tasks\main.py changed, reloading.
INFO 2021-02-01 10:41:52,034 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:42:08,364 autoreload 217 C:\Users\LiZ\Desktop\lgshop\celery_tasks\main.py changed, reloading.
INFO 2021-02-01 10:42:09,720 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 10:42:11,379 basehttp 154 "GET /image_codes/b25fd6af-e334-41ef-914f-80d85d9ec43d/ HTTP/1.1" 200 2966
INFO 2021-02-01 10:42:24,845 autoreload 217 C:\Users\LiZ\Desktop\lgshop\celery_tasks\main.py changed, reloading.
INFO 2021-02-01 10:42:26,136 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:51:40,846 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:51:52,282 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
INFO 2021-02-01 14:51:52,490 basehttp 154 "GET /static/js/login.js HTTP/1.1" 200 1560
INFO 2021-02-01 14:51:52,491 basehttp 154 "GET /static/images/2.png HTTP/1.1" 200 6015
INFO 2021-02-01 14:55:07,658 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:55:09,058 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:56:02,070 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:56:03,346 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:56:54,735 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:56:56,089 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:58:36,957 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:58:38,448 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:58:48,588 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:58:49,973 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:59:06,600 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:59:08,044 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:59:25,096 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:59:26,514 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 14:59:44,810 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 14:59:46,233 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:00:15,487 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:00:16,895 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:00:27,019 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:00:28,453 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:01:25,608 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:01:27,068 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:01:52,484 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:01:53,816 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:04:06,926 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:04:08,385 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:04:38,636 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:04:39,955 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:05:11,879 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:05:13,170 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:06:25,564 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:06:26,875 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:07:08,995 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:07:10,354 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:07:21,431 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-02-01 15:07:25,876 log 228 Forbidden (CSRF token missing or incorrect.): /users/login/
WARNING 2021-02-01 15:07:25,877 basehttp 154 "POST /users/login/ HTTP/1.1" 403 2513
INFO 2021-02-01 15:08:54,501 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:09:09,533 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
ERROR 2021-02-01 15:09:13,589 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LoginView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-01 15:09:13,590 basehttp 154 "POST /users/login/ HTTP/1.1" 500 64666
INFO 2021-02-01 15:10:17,610 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:10:19,029 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:10:22,835 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
ERROR 2021-02-01 15:10:29,768 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LoginView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-01 15:10:29,769 basehttp 154 "POST /users/login/ HTTP/1.1" 500 64664
INFO 2021-02-01 15:11:12,455 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 15:11:12,769 basehttp 154 "GET /image_codes/013d3c47-3e6d-4b58-8792-04483ba5433f/ HTTP/1.1" 200 2942
INFO 2021-02-01 15:11:16,774 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:11:19,403 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:11:24,133 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:11:33,227 basehttp 154 "GET /image_codes/67303303-c855-43cf-b277-372f98e53cdf/ HTTP/1.1" 200 3157
INFO 2021-02-01 15:11:34,995 basehttp 154 "GET /image_codes/5df03a2e-2d74-4be2-969e-c8835494e3b8/ HTTP/1.1" 200 3805
INFO 2021-02-01 15:11:41,124 basehttp 154 "GET /sms_codes/15838618208/?uuid=5df03a2e-2d74-4be2-969e-c8835494e3b8&image_code=mfjw HTTP/1.1" 200 63
INFO 2021-02-01 15:12:41,145 basehttp 154 "GET /image_codes/6ba8e759-3362-4100-8296-0549b147822c/ HTTP/1.1" 200 2551
INFO 2021-02-01 15:12:43,180 basehttp 154 "GET /sms_codes/15838618208/?uuid=6ba8e759-3362-4100-8296-0549b147822c&image_code=mfjw HTTP/1.1" 200 84
INFO 2021-02-01 15:12:46,059 basehttp 154 "GET /sms_codes/15838618208/?uuid=6ba8e759-3362-4100-8296-0549b147822c&image_code=mfjw HTTP/1.1" 200 78
INFO 2021-02-01 15:12:48,516 basehttp 154 "GET /image_codes/0b98b6f4-1cf9-4e34-86bf-fd2360e07061/ HTTP/1.1" 200 3419
INFO 2021-02-01 15:12:54,090 basehttp 154 "GET /sms_codes/15838618208/?uuid=0b98b6f4-1cf9-4e34-86bf-fd2360e07061&image_code=qtu8 HTTP/1.1" 200 63
INFO 2021-02-01 15:13:54,108 basehttp 154 "GET /image_codes/c7708c82-9e63-4123-a5d6-0537aaf14406/ HTTP/1.1" 200 2859
INFO 2021-02-01 15:18:15,860 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\verifications\views.py changed, reloading.
INFO 2021-02-01 15:18:17,305 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:18:38,058 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:18:42,288 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-01 15:18:42,607 basehttp 154 "GET /image_codes/c72c58ae-f162-48b6-a2bd-607b80ec1f71/ HTTP/1.1" 200 2953
INFO 2021-02-01 15:18:45,133 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:18:51,284 basehttp 154 "GET /image_codes/a73a6e38-79db-4c6c-9617-8ddc263729dc/ HTTP/1.1" 200 3106
INFO 2021-02-01 15:18:52,356 basehttp 154 "GET /image_codes/d7ff6065-03c5-4417-adba-311d0980df95/ HTTP/1.1" 200 3245
INFO 2021-02-01 15:18:57,294 basehttp 154 "GET /sms_codes/17710709974/?uuid=d7ff6065-03c5-4417-adba-311d0980df95&image_code=xgad HTTP/1.1" 200 63
INFO 2021-02-01 15:19:12,342 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:19:13,590 basehttp 154 "GET /users/usernames/lizhun/count/ HTTP/1.1" 200 41
INFO 2021-02-01 15:19:13,847 basehttp 154 "POST /users/register/ HTTP/1.1" 302 0
INFO 2021-02-01 15:19:13,866 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 15:19:13,929 basehttp 154 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2021-02-01 15:19:14,096 basehttp 154 "GET /static/js/slide.js HTTP/1.1" 200 1822
INFO 2021-02-01 15:19:14,097 basehttp 154 "GET /static/js/index.js HTTP/1.1" 200 1143
INFO 2021-02-01 15:19:14,124 basehttp 154 "GET /static/images/goods/goods001.jpg HTTP/1.1" 200 5391
INFO 2021-02-01 15:19:14,124 basehttp 154 "GET /static/images/goods/goods002.jpg HTTP/1.1" 200 5377
INFO 2021-02-01 15:19:14,139 basehttp 154 "GET /static/images/banner01.jpg HTTP/1.1" 200 23658
INFO 2021-02-01 15:19:14,140 basehttp 154 "GET /static/images/slide01.jpg HTTP/1.1" 200 67813
INFO 2021-02-01 15:19:14,142 basehttp 154 "GET /static/images/slide03.jpg HTTP/1.1" 200 70152
INFO 2021-02-01 15:19:14,144 basehttp 154 "GET /static/images/slide02.jpg HTTP/1.1" 200 89905
INFO 2021-02-01 15:19:14,146 basehttp 154 "GET /static/images/adv01.jpg HTTP/1.1" 200 39831
INFO 2021-02-01 15:19:14,148 basehttp 154 "GET /static/images/slide04.jpg HTTP/1.1" 200 107973
INFO 2021-02-01 15:19:14,151 basehttp 154 "GET /static/images/goods/goods003.jpg HTTP/1.1" 200 8579
INFO 2021-02-01 15:19:14,159 basehttp 154 "GET /static/images/goods/goods004.jpg HTTP/1.1" 200 6565
INFO 2021-02-01 15:19:14,160 basehttp 154 "GET /static/images/goods/goods005.jpg HTTP/1.1" 200 7578
INFO 2021-02-01 15:19:14,164 basehttp 154 "GET /static/images/goods/goods008.jpg HTTP/1.1" 200 7072
INFO 2021-02-01 15:19:14,165 basehttp 154 "GET /static/images/banner02.jpg HTTP/1.1" 200 26729
INFO 2021-02-01 15:19:14,165 basehttp 154 "GET /static/images/banner03.jpg HTTP/1.1" 200 22681
INFO 2021-02-01 15:19:14,167 basehttp 154 "GET /static/images/goods/goods009.jpg HTTP/1.1" 200 8738
INFO 2021-02-01 15:19:25,723 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
ERROR 2021-02-01 15:19:31,733 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LoginView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-01 15:19:31,734 basehttp 154 "POST /users/login/ HTTP/1.1" 500 64664
INFO 2021-02-01 15:21:18,421 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:21:20,081 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:21:51,198 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:21:51,872 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
ERROR 2021-02-01 15:21:58,285 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LoginView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-01 15:21:58,286 basehttp 154 "POST /users/login/ HTTP/1.1" 500 64664
INFO 2021-02-01 15:22:14,064 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:22:15,613 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:22:25,911 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:22:27,372 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:22:53,370 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:22:54,819 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:23:09,157 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:23:10,479 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:23:45,586 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:23:47,057 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:25:51,778 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2734
INFO 2021-02-01 15:25:57,772 basehttp 154 "POST /users/login/ HTTP/1.1" 200 2734
WARNING 2021-02-01 15:25:57,957 log 228 Not Found: /users/images/login_banner.png
WARNING 2021-02-01 15:25:57,961 log 228 Not Found: /users/images/QQ-weixin.png
WARNING 2021-02-01 15:25:57,963 log 228 Not Found: /users/images/icons02.png
WARNING 2021-02-01 15:25:57,963 basehttp 154 "GET /users/images/login_banner.png HTTP/1.1" 404 3123
WARNING 2021-02-01 15:25:57,964 basehttp 154 "GET /users/images/QQ-weixin.png HTTP/1.1" 404 3114
WARNING 2021-02-01 15:25:57,965 basehttp 154 "GET /users/images/icons02.png HTTP/1.1" 404 3108
INFO 2021-02-01 15:26:19,049 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:26:20,421 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:26:22,859 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:26:24,255 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:26:53,336 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:26:54,739 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:27:04,762 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:27:06,332 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:27:16,311 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-01 15:27:16,327 basehttp 154 "GET / HTTP/1.1" 200 38951
WARNING 2021-02-01 15:27:16,636 log 228 Not Found: /images/icons.png
WARNING 2021-02-01 15:27:16,636 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
INFO 2021-02-01 15:35:49,077 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:36:06,305 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-01 15:36:06,328 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 15:40:49,344 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:40:50,874 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:41:07,747 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:41:09,245 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:41:45,141 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:41:46,657 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:42:17,419 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:42:18,979 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:42:21,939 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:42:23,326 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:43:48,985 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:43:50,309 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:44:08,177 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:44:09,669 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:44:16,318 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:44:17,737 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 15:44:45,624 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 15:45:19,875 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-01 15:45:19,884 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 15:46:11,119 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-01 15:46:11,132 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 15:47:07,310 basehttp 154 "POST /users/login/ HTTP/1.1" 200 2960
INFO 2021-02-01 15:48:00,370 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 15:48:01,592 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:06:56,979 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:06:58,283 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:07:31,551 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:07:33,061 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:08:05,247 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:08:06,708 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:08:39,827 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:08:41,293 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:08:53,055 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:09:07,458 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
ERROR 2021-02-01 16:09:21,421 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 45, in post
    user = authenticate(username=username, password=password)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'users.utils.UsernameMobileBackend'; 'users.utils' is not a package
ERROR 2021-02-01 16:09:21,424 basehttp 154 "POST /users/login/ HTTP/1.1" 500 111346
INFO 2021-02-01 16:11:05,703 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:11:13,066 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
WARNING 2021-02-01 16:11:13,319 log 228 Not Found: /users/images/icons02.png
WARNING 2021-02-01 16:11:13,320 log 228 Not Found: /users/images/login_banner.png
WARNING 2021-02-01 16:11:13,323 log 228 Not Found: /users/images/QQ-weixin.png
WARNING 2021-02-01 16:11:13,324 basehttp 154 "GET /users/images/icons02.png HTTP/1.1" 404 3108
WARNING 2021-02-01 16:11:13,324 basehttp 154 "GET /users/images/login_banner.png HTTP/1.1" 404 3123
WARNING 2021-02-01 16:11:13,326 basehttp 154 "GET /users/images/QQ-weixin.png HTTP/1.1" 404 3114
ERROR 2021-02-01 16:11:24,161 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 45, in post
    user = authenticate(username=username, password=password)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\utils.py", line 3, in <module>
    from .models import User
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2021-02-01 16:11:24,167 basehttp 154 "POST /users/login/ HTTP/1.1" 500 155955
INFO 2021-02-01 16:12:53,529 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:13:10,261 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
ERROR 2021-02-01 16:13:22,845 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 45, in post
    user = authenticate(username=username, password=password)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.users.utils.UsernameMobileBackend'; 'apps.users.utils' is not a package
ERROR 2021-02-01 16:13:22,848 basehttp 154 "POST /users/login/ HTTP/1.1" 500 111486
INFO 2021-02-01 16:14:12,695 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 16:14:13,959 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:14:31,750 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 16:14:33,232 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:14:51,455 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 16:14:52,953 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:14:57,776 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
ERROR 2021-02-01 16:15:07,849 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 44, in post
    user = authenticate(username=username, password=password)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'apps.users.utils.UsernameMobileBackend'; 'apps.users.utils' is not a package
ERROR 2021-02-01 16:15:07,854 basehttp 154 "POST /users/login/ HTTP/1.1" 500 111500
INFO 2021-02-01 16:16:03,323 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\utils.py changed, reloading.
INFO 2021-02-01 16:16:04,663 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:16:10,205 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
ERROR 2021-02-01 16:16:20,816 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 44, in post
    user = authenticate(username=username, password=password)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\contrib\auth\__init__.py", line 21, in load_backend
    return import_string(path)()
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "D:\Alltools\conda\unzip\envs\py3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\utils.py", line 3, in <module>
    from .models import User
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\models.py", line 6, in <module>
    class User(AbstractUser):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class apps.users.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
ERROR 2021-02-01 16:16:20,822 basehttp 154 "POST /users/login/ HTTP/1.1" 500 156276
INFO 2021-02-01 16:19:09,884 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:19:13,510 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:19:19,802 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
ERROR 2021-02-01 16:19:29,628 log 228 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 59, in post
    return redirect(reverse('contents:index'))
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'contents' is not a registered namespace
ERROR 2021-02-01 16:19:29,631 basehttp 154 "POST /users/login/ HTTP/1.1" 500 96507
INFO 2021-02-01 16:19:57,314 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-01 16:19:58,634 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-01 16:20:01,588 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-01 16:20:10,312 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-01 16:20:10,324 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-01 16:20:40,971 autoreload 217 C:\Users\LiZ\Desktop\lgshop\lgshop\dev.py changed, reloading.
INFO 2021-02-01 16:20:42,516 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:11:42,757 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:11:48,424 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-02 10:11:48,425 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:11:48,621 basehttp 154 "GET /static/js/register.js HTTP/1.1" 304 0
WARNING 2021-02-02 10:11:50,738 log 228 Not Found: /favicon.ico
WARNING 2021-02-02 10:11:50,739 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-02-02 10:11:57,776 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
ERROR 2021-02-02 10:11:57,943 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\contents\views.py", line 9, in get
    return render(request, 'index.html')
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
ERROR 2021-02-02 10:11:57,949 basehttp 154 "GET / HTTP/1.1" 500 132578
INFO 2021-02-02 10:13:17,089 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-02-02 10:13:20,407 log 228 Internal Server Error: /
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\contents\views.py", line 9, in get
    return render(request, 'index.html')
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\resolvers.py", line 673, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'info' not found. 'info' is not a valid view function or pattern name.
ERROR 2021-02-02 10:13:20,414 basehttp 154 "GET / HTTP/1.1" 500 132592
INFO 2021-02-02 10:13:47,493 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-02 10:13:51,510 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:13:58,181 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 10:13:58,191 basehttp 154 "GET / HTTP/1.1" 200 38951
INFO 2021-02-02 10:41:21,114 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:41:26,476 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:41:28,710 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:41:35,925 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 10:41:35,936 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:41:39,737 basehttp 154 "GET / HTTP/1.1" 200 38899
WARNING 2021-02-02 10:41:39,943 log 228 Not Found: /images/icons.png
WARNING 2021-02-02 10:41:39,944 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
INFO 2021-02-02 10:41:40,144 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:41:40,418 basehttp 154 "GET / HTTP/1.1" 200 38899
WARNING 2021-02-02 10:41:40,576 log 228 Not Found: /images/icons.png
WARNING 2021-02-02 10:41:40,577 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
INFO 2021-02-02 10:41:40,789 basehttp 154 "GET / HTTP/1.1" 200 38899
WARNING 2021-02-02 10:41:41,138 log 228 Not Found: /images/icons.png
WARNING 2021-02-02 10:41:41,138 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
ERROR 2021-02-02 10:41:42,112 log 228 Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LogoutView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-02 10:41:42,113 basehttp 154 "GET /users/logout/ HTTP/1.1" 500 62587
INFO 2021-02-02 10:43:56,264 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-02-02 10:43:58,332 log 228 Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.LogoutView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-02 10:43:58,333 basehttp 154 "GET /users/logout/ HTTP/1.1" 500 62370
INFO 2021-02-02 10:44:55,165 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:44:56,654 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-02-02 10:45:01,094 log 228 Internal Server Error: /users/logout/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 30, in get
    response = redirect(reverse('contents:index'))
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'contents' is not a registered namespace
ERROR 2021-02-02 10:45:01,096 basehttp 154 "GET /users/logout/ HTTP/1.1" 500 92808
INFO 2021-02-02 10:45:11,762 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:45:15,839 basehttp 154 "GET /users/logout/ HTTP/1.1" 302 0
INFO 2021-02-02 10:45:15,861 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:45:54,190 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:45:55,630 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:45:59,832 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:46:10,081 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 10:46:10,098 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:46:11,730 basehttp 154 "GET /users/logout/ HTTP/1.1" 302 0
INFO 2021-02-02 10:46:11,740 basehttp 154 "GET / HTTP/1.1" 200 38899
INFO 2021-02-02 10:49:59,481 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\urls.py changed, reloading.
INFO 2021-02-02 10:50:01,081 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:50:56,382 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\urls.py changed, reloading.
INFO 2021-02-02 10:50:57,970 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:51:19,160 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\urls.py changed, reloading.
INFO 2021-02-02 10:51:20,596 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-02-02 10:52:17,964 log 228 Internal Server Error: /users/info/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view users.views.UserInfotView didn't return an HttpResponse object. It returned None instead.
ERROR 2021-02-02 10:52:17,965 basehttp 154 "GET /users/info/ HTTP/1.1" 500 61813
INFO 2021-02-02 10:52:40,566 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:52:41,791 autoreload 597 Watching for file changes with StatReloader
ERROR 2021-02-02 10:52:43,900 log 228 Internal Server Error: /users/info/
Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\LiZ\Desktop\lgshop\apps\users\views.py", line 21, in get
    return render(request, 'user_center_info.html')
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Alltools\conda\unzip\envs\py3\lib\site-packages\django\urls\base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'contents' is not a registered namespace
ERROR 2021-02-02 10:52:43,906 basehttp 154 "GET /users/info/ HTTP/1.1" 500 137014
INFO 2021-02-02 10:53:10,040 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 10:53:10,244 basehttp 154 "GET /static/js/user_center_info.js HTTP/1.1" 200 2891
INFO 2021-02-02 10:57:05,652 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:57:07,107 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:57:28,471 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:57:30,098 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:57:35,198 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 10:57:36,718 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:57:41,465 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:57:48,629 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 10:57:48,642 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 10:57:51,264 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 10:59:23,701 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 10:59:30,833 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 10:59:34,663 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 10:59:37,622 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 10:59:42,730 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 10:59:42,744 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 10:59:44,634 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 11:00:21,807 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-02-02 11:00:29,395 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-02-02 11:00:32,366 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 11:00:32,430 basehttp 154 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2021-02-02 11:00:32,430 basehttp 154 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2021-02-02 11:00:32,431 basehttp 154 "GET /static/css/main.css HTTP/1.1" 200 40091
INFO 2021-02-02 11:00:32,433 basehttp 154 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2021-02-02 11:00:32,540 basehttp 154 "GET /static/images/icons.png HTTP/1.1" 200 7740
INFO 2021-02-02 11:00:32,549 basehttp 154 "GET /static/images/down.png HTTP/1.1" 200 1064
INFO 2021-02-02 11:00:32,558 basehttp 154 "GET /static/images/clock.jpg HTTP/1.1" 200 2235
INFO 2021-02-02 11:00:32,566 basehttp 154 "GET /static/images/shop_cart.png HTTP/1.1" 200 1317
INFO 2021-02-02 11:00:32,572 basehttp 154 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2021-02-02 11:00:32,577 basehttp 154 "GET /static/images/selected.png HTTP/1.1" 200 1060
INFO 2021-02-02 11:00:32,578 basehttp 154 "GET /static/images/interval_line.png HTTP/1.1" 200 1123
INFO 2021-02-02 11:00:32,582 basehttp 154 "GET /static/images/QQ-weixin.png HTTP/1.1" 200 1816
INFO 2021-02-02 11:00:32,585 basehttp 154 "GET /static/images/register_banner.png HTTP/1.1" 200 54894
INFO 2021-02-02 11:00:32,588 basehttp 154 "GET /static/images/pay_icons.png HTTP/1.1" 200 11917
INFO 2021-02-02 11:00:32,590 basehttp 154 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
INFO 2021-02-02 11:00:32,591 basehttp 154 "GET /static/images/edit.png HTTP/1.1" 200 1244
INFO 2021-02-02 11:00:32,601 basehttp 154 "GET /static/images/login_banner.png HTTP/1.1" 200 319312
INFO 2021-02-02 11:00:32,603 basehttp 154 "GET /static/images/find-password.png HTTP/1.1" 200 6186
INFO 2021-02-02 11:00:32,605 basehttp 154 "GET /static/images/success.png HTTP/1.1" 200 2738
INFO 2021-02-02 11:00:32,607 basehttp 154 "GET /static/images/stars.png HTTP/1.1" 200 2688
INFO 2021-02-02 11:00:32,608 basehttp 154 "GET /static/images/shine.png HTTP/1.1" 200 1270
INFO 2021-02-02 11:00:32,608 basehttp 154 "GET /static/images/time_count_bg.png HTTP/1.1" 200 1332
INFO 2021-02-02 11:00:32,614 basehttp 154 "GET /static/images/arrow.png HTTP/1.1" 200 985
INFO 2021-02-02 11:00:32,616 basehttp 154 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-02-02 11:00:32,619 basehttp 154 "GET /static/js/user_center_info.js HTTP/1.1" 200 2904
INFO 2021-02-02 11:00:32,622 basehttp 154 "GET /static/images/1.png HTTP/1.1" 200 3555
INFO 2021-02-02 11:00:32,641 basehttp 154 "GET /static/images/icons.png HTTP/1.1" 200 7740
INFO 2021-02-02 11:00:32,642 basehttp 154 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
WARNING 2021-02-02 11:00:34,148 log 228 Not Found: /favicon.ico
WARNING 2021-02-02 11:00:34,149 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-02-02 11:00:38,243 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 11:00:38,296 basehttp 154 "GET /static/js/jquery-1.12.4.min.js HTTP/1.1" 200 97163
INFO 2021-02-02 11:00:38,348 basehttp 154 "GET /static/js/slide.js HTTP/1.1" 200 1822
INFO 2021-02-02 11:00:38,438 basehttp 154 "GET /static/js/index.js HTTP/1.1" 200 1143
INFO 2021-02-02 11:00:38,451 basehttp 154 "GET /static/images/goods/goods001.jpg HTTP/1.1" 200 5391
INFO 2021-02-02 11:00:38,452 basehttp 154 "GET /static/images/goods/goods002.jpg HTTP/1.1" 200 5377
INFO 2021-02-02 11:00:38,455 basehttp 154 "GET /static/images/slide01.jpg HTTP/1.1" 200 67813
INFO 2021-02-02 11:00:38,456 basehttp 154 "GET /static/images/slide02.jpg HTTP/1.1" 200 89905
INFO 2021-02-02 11:00:38,457 basehttp 154 "GET /static/images/slide03.jpg HTTP/1.1" 200 70152
INFO 2021-02-02 11:00:38,458 basehttp 154 "GET /static/images/slide04.jpg HTTP/1.1" 200 107973
INFO 2021-02-02 11:00:38,465 basehttp 154 "GET /static/images/adv01.jpg HTTP/1.1" 200 39831
INFO 2021-02-02 11:00:38,471 basehttp 154 "GET /static/images/banner01.jpg HTTP/1.1" 200 23658
INFO 2021-02-02 11:00:38,475 basehttp 154 "GET /static/images/goods/goods003.jpg HTTP/1.1" 200 8579
INFO 2021-02-02 11:00:38,477 basehttp 154 "GET /static/images/goods/goods004.jpg HTTP/1.1" 200 6565
INFO 2021-02-02 11:00:38,480 basehttp 154 "GET /static/images/goods/goods005.jpg HTTP/1.1" 200 7578
INFO 2021-02-02 11:00:38,483 basehttp 154 "GET /static/images/banner02.jpg HTTP/1.1" 200 26729
INFO 2021-02-02 11:00:38,486 basehttp 154 "GET /static/images/goods/goods008.jpg HTTP/1.1" 200 7072
INFO 2021-02-02 11:00:38,487 basehttp 154 "GET /static/images/banner03.jpg HTTP/1.1" 200 22681
INFO 2021-02-02 11:00:38,489 basehttp 154 "GET /static/images/goods/goods009.jpg HTTP/1.1" 200 8738
INFO 2021-02-02 11:00:40,940 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 11:03:50,817 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 11:03:52,216 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 11:04:10,580 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 11:04:11,947 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 11:04:33,986 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 11:04:35,387 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 11:11:53,192 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 11:11:57,201 basehttp 154 "GET /users/logout/ HTTP/1.1" 302 0
INFO 2021-02-02 11:11:57,225 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 11:11:58,879 basehttp 154 "GET /users/info/ HTTP/1.1" 302 0
INFO 2021-02-02 11:11:58,892 basehttp 154 "GET /users/login/?next=/users/info/ HTTP/1.1" 200 2920
INFO 2021-02-02 11:11:59,004 basehttp 154 "GET /static/js/login.js HTTP/1.1" 200 1560
INFO 2021-02-02 11:11:59,106 basehttp 154 "GET /static/images/2.png HTTP/1.1" 200 6015
INFO 2021-02-02 11:13:48,843 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 11:13:50,218 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 11:14:13,167 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 11:14:14,596 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 13:59:29,255 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 13:59:35,023 basehttp 154 "POST /users/login/?next=/users/info/ HTTP/1.1" 200 2960
INFO 2021-02-02 13:59:49,527 basehttp 154 "POST /users/login/?next=/users/info/ HTTP/1.1" 200 2960
INFO 2021-02-02 13:59:54,635 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
WARNING 2021-02-02 13:59:54,811 log 228 Not Found: /users/images/login_banner.png
WARNING 2021-02-02 13:59:54,813 log 228 Not Found: /users/images/icons02.png
WARNING 2021-02-02 13:59:54,816 log 228 Not Found: /users/images/QQ-weixin.png
WARNING 2021-02-02 13:59:54,818 basehttp 154 "GET /users/images/login_banner.png HTTP/1.1" 404 3469
WARNING 2021-02-02 13:59:54,818 basehttp 154 "GET /users/images/icons02.png HTTP/1.1" 404 3454
WARNING 2021-02-02 13:59:54,819 basehttp 154 "GET /users/images/QQ-weixin.png HTTP/1.1" 404 3460
INFO 2021-02-02 14:00:00,983 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 14:00:00,997 basehttp 154 "GET / HTTP/1.1" 200 38943
WARNING 2021-02-02 14:00:01,212 log 228 Not Found: /images/icons.png
WARNING 2021-02-02 14:00:01,213 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
INFO 2021-02-02 14:00:05,895 basehttp 154 "GET / HTTP/1.1" 200 38943
WARNING 2021-02-02 14:00:06,074 log 228 Not Found: /images/icons.png
WARNING 2021-02-02 14:00:06,074 basehttp 154 "GET /images/icons.png HTTP/1.1" 404 2627
INFO 2021-02-02 14:00:08,074 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 14:00:08,117 basehttp 154 "GET /static/js/user_center_info.js HTTP/1.1" 304 0
WARNING 2021-02-02 14:00:08,240 log 228 Not Found: /users/images/icons.png
WARNING 2021-02-02 14:00:08,242 log 228 Not Found: /users/images/left_bg.jpg
WARNING 2021-02-02 14:00:08,243 basehttp 154 "GET /users/images/left_bg.jpg HTTP/1.1" 404 3454
WARNING 2021-02-02 14:00:08,244 basehttp 154 "GET /users/images/icons.png HTTP/1.1" 404 3448
INFO 2021-02-02 14:00:24,565 basehttp 154 "GET /users/info/ HTTP/1.1" 302 0
INFO 2021-02-02 14:00:24,575 basehttp 154 "GET /users/login/?next=/users/info/ HTTP/1.1" 200 2920
INFO 2021-02-02 14:00:24,635 basehttp 154 "GET /static/css/reset.css HTTP/1.1" 200 638
INFO 2021-02-02 14:00:24,638 basehttp 154 "GET /static/css/main.css HTTP/1.1" 200 40091
INFO 2021-02-02 14:00:24,639 basehttp 154 "GET /static/js/axios-0.18.0.min.js HTTP/1.1" 200 12941
INFO 2021-02-02 14:00:24,643 basehttp 154 "GET /static/js/vue-2.5.16.js HTTP/1.1" 200 289307
INFO 2021-02-02 14:00:24,651 basehttp 154 "GET /static/js/common.js HTTP/1.1" 200 891
INFO 2021-02-02 14:00:24,658 basehttp 154 "GET /static/js/login.js HTTP/1.1" 200 1560
INFO 2021-02-02 14:00:24,668 basehttp 154 "GET /static/images/2.png HTTP/1.1" 200 6015
INFO 2021-02-02 14:00:24,672 basehttp 154 "GET /static/images/icons02.png HTTP/1.1" 200 3935
INFO 2021-02-02 14:00:24,672 basehttp 154 "GET /static/images/QQ-weixin.png HTTP/1.1" 200 1816
INFO 2021-02-02 14:00:24,674 basehttp 154 "GET /static/images/login_banner.png HTTP/1.1" 200 319312
INFO 2021-02-02 14:00:34,940 basehttp 154 "POST /users/login/?next=/users/info/ HTTP/1.1" 302 0
INFO 2021-02-02 14:00:34,951 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 14:00:34,979 basehttp 154 "GET /static/images/1.png HTTP/1.1" 200 3555
INFO 2021-02-02 14:00:34,979 basehttp 154 "GET /static/js/user_center_info.js HTTP/1.1" 200 2904
INFO 2021-02-02 14:00:34,988 basehttp 154 "GET /static/images/icons.png HTTP/1.1" 200 7740
INFO 2021-02-02 14:00:34,989 basehttp 154 "GET /static/images/left_bg.jpg HTTP/1.1" 200 1367
INFO 2021-02-02 14:00:45,897 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 14:00:48,521 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 14:00:55,277 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 14:00:55,288 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 14:01:45,370 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 14:01:46,824 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 14:02:24,224 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 14:02:25,460 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 14:02:47,218 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 14:02:48,477 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 14:03:04,969 autoreload 217 C:\Users\LiZ\Desktop\lgshop\apps\users\views.py changed, reloading.
INFO 2021-02-02 14:03:06,494 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-02 14:03:12,085 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 14:03:13,874 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-02 14:03:18,661 basehttp 154 "POST /users/login/ HTTP/1.1" 200 2960
INFO 2021-02-02 14:03:26,604 basehttp 154 "POST /users/login/ HTTP/1.1" 302 0
INFO 2021-02-02 14:03:26,614 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 14:03:28,569 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-02 14:03:30,117 basehttp 154 "GET /users/logout/ HTTP/1.1" 302 0
INFO 2021-02-02 14:03:30,126 basehttp 154 "GET / HTTP/1.1" 200 38943
INFO 2021-02-02 14:03:31,297 basehttp 154 "GET /users/info/ HTTP/1.1" 302 0
INFO 2021-02-02 14:03:31,308 basehttp 154 "GET /users/login/?next=/users/info/ HTTP/1.1" 200 2920
INFO 2021-02-02 14:03:37,762 basehttp 154 "POST /users/login/?next=/users/info/ HTTP/1.1" 302 0
INFO 2021-02-02 14:03:37,776 basehttp 154 "GET /users/info/ HTTP/1.1" 200 5548
INFO 2021-02-04 09:06:18,306 autoreload 597 Watching for file changes with StatReloader
INFO 2021-02-04 09:06:30,653 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
WARNING 2021-02-04 09:06:30,991 log 228 Not Found: /users/images/login_banner.png
WARNING 2021-02-04 09:06:30,992 log 228 Not Found: /users/images/QQ-weixin.png
WARNING 2021-02-04 09:06:30,993 log 228 Not Found: /users/images/icons02.png
WARNING 2021-02-04 09:06:30,994 basehttp 154 "GET /users/images/login_banner.png HTTP/1.1" 404 3469
WARNING 2021-02-04 09:06:30,994 basehttp 154 "GET /users/images/QQ-weixin.png HTTP/1.1" 404 3460
WARNING 2021-02-04 09:06:30,994 basehttp 154 "GET /users/images/icons02.png HTTP/1.1" 404 3454
WARNING 2021-02-04 09:06:32,537 log 228 Not Found: /favicon.ico
WARNING 2021-02-04 09:06:32,538 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2612
INFO 2021-02-04 10:33:20,001 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-02-04 10:33:33,189 log 228 Not Found: /images/
WARNING 2021-02-04 10:33:33,190 basehttp 154 "GET /images/ HTTP/1.1" 404 2600
WARNING 2021-02-04 10:33:42,065 log 228 Not Found: /image_codes/
WARNING 2021-02-04 10:33:42,065 basehttp 154 "GET /image_codes/ HTTP/1.1" 404 2615
WARNING 2021-02-04 10:34:34,110 log 228 Not Found: /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d
WARNING 2021-02-04 10:34:34,110 basehttp 154 "GET /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d HTTP/1.1" 404 2740
WARNING 2021-02-04 10:34:38,168 log 228 Not Found: /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/
WARNING 2021-02-04 10:34:38,169 basehttp 154 "GET /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/ HTTP/1.1" 404 2743
WARNING 2021-02-04 10:34:54,166 log 228 Not Found: /image_codes/
WARNING 2021-02-04 10:34:54,167 basehttp 154 "GET /image_codes/?uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/ HTTP/1.1" 404 2658
WARNING 2021-02-04 10:35:17,370 log 228 Not Found: /image_codes/
WARNING 2021-02-04 10:35:17,370 basehttp 154 "GET /image_codes/?uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d HTTP/1.1" 404 2657
WARNING 2021-02-04 10:35:20,618 log 228 Not Found: /image_codes/
WARNING 2021-02-04 10:35:20,618 basehttp 154 "GET /image_codes/?uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/ HTTP/1.1" 404 2658
WARNING 2021-02-04 10:35:35,634 log 228 Not Found: /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/
WARNING 2021-02-04 10:35:35,634 basehttp 154 "GET /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/ HTTP/1.1" 404 2743
WARNING 2021-02-04 10:39:20,389 log 228 Not Found: /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/
WARNING 2021-02-04 10:39:20,389 basehttp 154 "GET /image_codes/uuid=43df7a5a-ac9d-4152-a5d6-6a73ac4a326d/ HTTP/1.1" 404 2743
INFO 2021-02-04 10:39:34,311 basehttp 154 "GET /users/login/ HTTP/1.1" 200 2920
INFO 2021-02-04 10:39:35,261 basehttp 154 "GET /users/register/ HTTP/1.1" 200 5619
INFO 2021-02-04 10:39:35,388 basehttp 154 "GET /static/js/register.js HTTP/1.1" 200 7453
INFO 2021-02-04 10:39:35,801 basehttp 154 "GET /image_codes/8e50768f-c22c-4933-be04-3060e833f667/ HTTP/1.1" 200 3189
WARNING 2021-02-04 10:39:37,780 basehttp 154 "GET /static/js/axios.min.map HTTP/1.1" 404 1672
INFO 2021-02-04 10:39:39,325 basehttp 154 "GET /image_codes/b8b17506-1817-4d31-9219-c0902ae6dbda/ HTTP/1.1" 200 3452
INFO 2021-02-04 10:39:53,828 basehttp 154 "GET /image_codes/b8b17506-1817-4d31-9219-c0902ae6dbda/ HTTP/1.1" 200 3093
INFO 2021-02-04 10:39:56,388 basehttp 154 "GET /image_codes/b8b17506-1817-4d31-9219-c0902ae6dbda/ HTTP/1.1" 200 3132
